### ISSUE TITLE
Unable to initialize the API: createType(ProductId)

### ISSUE THREAD

**Issue by sebastinez** [substrate-developer-hub/substrate-enterprise-sample#68]
Hello Substrate Developers,

First of all thank you very much for this sample, it really helped me a lot to understand some things about how different pallets work together and how I could apply it to my use case.

Following the guided demo, I wanted to inspect a newly generated Blockhash with Polkadot.js, but when I tried to complete the following step:
![Screenshot from 2020-12-20 08-34-56](https://user-images.githubusercontent.com/7912302/102712247-5435a580-429e-11eb-86eb-bf3d7382f772.png)

I encountered myself with the following error:
![Screenshot from 2020-12-20 08-42-55](https://user-images.githubusercontent.com/7912302/102712366-74199900-429f-11eb-9a0f-19565bd499e1.png)

After some digging I understood that I had to provide the types, for the creation of the API, and made it work on the `substrate-front-end-template`, adding the `CUSTOM_TYPES` in the following file https://github.com/substrate-developer-hub/substrate-front-end-template/blob/master/src/config/development.json but I wanted to make it work with the Polkadot.js UI.
Could you give me a hint where I should be looking? I already messed around in the `/api/chain` folder adding types and new chains but didn't seem to have much effect..

Thank you very much!

**Comment by danforbes** [comment]
Hi, @sebastinez - great question and sorry we haven't made this easier to understand. You should be able to add the types here https://polkadot.js.org/apps/#/settings/developer under Settings > Developer. Please let me know if this helps.

**Comment by sebastinez** [comment]
Hi @danforbes, thank you very much for your help!
Yes this helped a lot and I could make it work.

Cheers!
