### ISSUE TITLE
Devspaces & Gitpod Integration

### ISSUE THREAD

**Issue by miseenplace** [substrate-developer-hub/substrate-enterprise-sample#69]
Could we please get devspaces.json and a dockerfile for this repo?

Additionally, a gitpod.yml would be amazing.

See:  [Substrate Node Template:  Issue 120](https://github.com/substrate-developer-hub/substrate-node-template/issues/120)

I think this will make it easier to spin up a demo instance for those interested in exploring the code and functionality.

**Comment by NukeManDan** [comment]
gitpod AFAIK is too underpowered to make this happen (build times are far too long and heavy). If I am wrong here, let's reopen! :+1:
