### ISSUE TITLE
Unable to load accounts in the frontend template

### ISSUE THREAD

**Issue by Yogisam72** [substrate-developer-hub/substrate-enterprise-sample#73]
![Screenshot (130)](https://user-images.githubusercontent.com/48612683/111145576-6c237980-85ae-11eb-8003-1d2335ff1142.png)

**Comment by NukeManDan** [comment]
@Yogisam72 this repo should be updated to substrate v3 soon, that may alleviate the issue.

Ideally a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) will help me help you 🙏🏼

**Comment by jimmychu0807** [comment]
closing this and superseded by: #74
