### ISSUE TITLE
Architecture doc for porting to v4

### ISSUE THREAD

**Issue by truedat101** [substrate-developer-hub/substrate-enterprise-sample#91]
I was evaluating the code and sample here and ran into problems #86 , which referred to #74 , and eventually realized (yesterday) this repository is not maintained, since it was marked as archived.

Could the owner provide some architecture design doc to support porting to v4?  I would like to fork this repository and carry it forward, or start from scratch.  Unfortunately/fortunately, this sample is exactly my use case, and I am evaluating substrate and other blockchains.  I would like to stick with substrate.  This is a very useful use case .  From a design perspective, a minimal porting guide to move this code base forward would be helpful.

**Comment by nuke-web3** [comment]
(#89) I hope that this project will be re-started from scratch, although at the time of writing there is no plan by the substrate developer hub org to do so. As I understand it, for moving to upcoming substrate v4 will be a very large refactor, and likely a rewrite from scratch will be easier. 

The general features (pallets, RPCs, and such in this repo) can be used as reference in whatever path you choose. The overall architecture could remain mostly the same, the implementation details will differ in breaking ways though. 

If you want to fork - there is no stopping you :wink: 
Here are a few helpful tips if you are trying to upgrade logic:
- FRAME v1 -> v2 : https://substrate.dev/rustdocs/latest/frame_support/attr.pallet.html#upgrade-guidelines
- Substrate v2->v3 : https://github.com/paritytech/substrate/blob/master/docs/Upgrading-2.0-to-3.0.md
  - There is no v4 release or upgrade guide at this time, but there likely will be one when that is released.
